#!/usr/bin/env ruby

$LOAD_PATH.unshift "./lib"

require "mine_prefs/symlinker"
require "mine_prefs/backup_agent"
require "mine_prefs/installation"
require "mine_prefs/installation_payload"
require "mine_prefs/target_file_remover"
require "fileutils"

source  = File.join(File.dirname(File.expand_path(__FILE__)), "RubyMineXX")
options = Dir[File.join(source, "options", "**", "*")].map { |file| file.gsub %r{.*/(options.*)}, '\1' }
target  = ENV['TARGET_DIR'] || Dir[File.expand_path(File.join("~", "Library", "Preferences", "RubyMine*"))].last

installation_payload = MinePrefs::InstallationPayload.new(
  target: target,
  source_location: source,
  files_to_install: [
    "keymaps",
    "codestyles",
    "templates",
  ] + options,
)

MinePrefs::Installation.new(
  installation_payload: installation_payload,
  install_commands: [
    MinePrefs::BackupAgent.new,
    MinePrefs::TargetFileRemover.new,
    MinePrefs::Symlinker.new
  ],
).install
