#!/usr/bin/env ruby

$LOAD_PATH.unshift "./lib"

require "mine_prefs"

source  = File.join(File.dirname(File.expand_path(__FILE__)), "RubyMineXX")
options = Dir[File.join(source, "options", "**", "*")].map { |file| file.gsub %r{.*/(options.*)}, '\1' }
target_location  = ENV['TARGET_DIR'] || Dir[File.expand_path(File.join("~", "Library", "Preferences", "RubyMine*"))].last

installation_payload = MinePrefs::InstallationPayload.new(
  target_location: target_location,
  source_location: source,
  files_to_install: [
    "keymaps",
    "codestyles",
    "templates",
  ] + options,
)

MinePrefs::Installation.new(
  installation_payload: installation_payload,
  install_commands: [
    MinePrefs::Commands::BackupAgent.new,
    MinePrefs::Commands::TargetFileRemover.new,
    MinePrefs::Commands::Symlinker.new
  ],
).install
