require "fileutils"
require "mine_prefs/installation"
require "mine_prefs/installation_payload"
require "mine_prefs/commands/symlink"
require "mine_prefs/commands/unsymlink"
require "mine_prefs/commands/backups/backup"
require "mine_prefs/commands/backups/restore"
require "mine_prefs/commands/backups/file"
